version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\winimerge\winimerge
shallow_clone: true
install:
- cmd: >-
    cd c:\projects\winimerge\

    hg clone https://bitbucket.org/winmerge/freeimage

build_script:
- cmd: >-
    cd c:\projects\winimerge\winimerge

    BuildBin.vs2017.cmd

    BuildArc.cmd
artifacts:
- path: Dist/winimerge-*-exe.zip
