version: 1.0.{build}
image: Visual Studio 2022
clone_folder: c:\projects\winimerge\winimerge
shallow_clone: true
install:
- cmd: >-
    cd c:\projects\winimerge\

    git clone https://github.com/winmerge/freeimage

build_script:
- cmd: >-
    cd c:\projects\winimerge\winimerge

    BuildBin.cmd

    BuildArc.cmd
artifacts:
- path: Dist/winimerge-*.zip
